#!/bin/bash

set -e

for i in solution.py test.py
do
  if ! test -f $i
  then
    echo "No solution.py"
    exit -1
  fi
done

echo "--- Running test.py ---"
if ! python test.py >/dev/null
then
  echo "Running test.py failed"
  exit -2
fi

echo "--- Running Tests ---"
for i in $(ls .test/test*.py)
do
	if ! python $i
	then
		echo "Test '$i' failed"
		exit -3
	fi
done
